# Generated by Django 3.2.16 on 2025-02-12 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
